# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"make_differentiation_matrices": "00_core.ipynb",
         "make_laplace_kernel": "00_core.ipynb",
         "p_shrink": "00_core.ipynb",
         "unwrap": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/shrinkwrap/"

git_url = "https://github.com/fastai/shrinkwrap/tree/master/"

def custom_doc_links(name): return None
